// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jenrawson.familyfridge.domain;

import com.jenrawson.familyfridge.domain.Person;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect PersonDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PersonDataOnDemand: @Component;
    
    private Random PersonDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Person> PersonDataOnDemand.data;
    
    public Person PersonDataOnDemand.getNewTransientPerson(int index) {
        com.jenrawson.familyfridge.domain.Person obj = new com.jenrawson.familyfridge.domain.Person();
        obj.setAccount(null);
        obj.setFirstName("firstName_" + index);
        obj.setLastName("lastName_" + index);
        obj.setNickName("nickName_" + index);
        obj.setUserId("userId_" + index);
        return obj;
    }
    
    public Person PersonDataOnDemand.getSpecificPerson(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Person obj = data.get(index);
        return Person.findPerson(obj.getId());
    }
    
    public Person PersonDataOnDemand.getRandomPerson() {
        init();
        Person obj = data.get(rnd.nextInt(data.size()));
        return Person.findPerson(obj.getId());
    }
    
    public boolean PersonDataOnDemand.modifyPerson(Person obj) {
        return false;
    }
    
    public void PersonDataOnDemand.init() {
        data = com.jenrawson.familyfridge.domain.Person.findPersonEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Person' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.jenrawson.familyfridge.domain.Person>();
        for (int i = 0; i < 10; i++) {
            com.jenrawson.familyfridge.domain.Person obj = getNewTransientPerson(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
