// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jenrawson.familyfridge.domain;

import com.jenrawson.familyfridge.domain.Person;

privileged aspect Account_Roo_JavaBean {
    
    public Person Account.getOwner() {
        return this.owner;
    }
    
    public void Account.setOwner(Person owner) {
        this.owner = owner;
    }
    
}
